### ISSUE TITLE
Long-living MongoDB connection death

### ISSUE THREAD

**Issue by One-Nub** [Pyrite-X/Pyrite#6]
The various mongo_*x* libraries in Dart seem to work fine for the most part at first glance. Mongo_go was ultimately the most stable. but I could not get it (without probably a lot of troubleshooting) to build and run on ARM-based CPUs.

The bot is currently using mongo_pool (which is a layer on top of mongo_dart), and it seems that something with MongoDB Atlas does not support the long-running connection style that the bot utilizes. Direct connections are (supposedly) closed after a query is made, but something in the cloud results in errors like this appearing with no failsafe to recover: 

```
[2024-01-04T03:48:33.278798] [SEVERE] [Alfred]: Unhandled Error: MongoDart Error: No master connection
[2024-01-04T03:48:33.279152] [SEVERE] [Alfred]: #0      ConnectionManager.masterConnectionVerified (package:mongo_dart/src/network/connection_manager.dart:19)
#1      Db._masterConnectionVerifiedAnyState (package:mongo_dart/src/database/db.dart:220)
#2      Db._masterConnectionVerified (package:mongo_dart/src/database/db.dart:213)
#3      Db.masterConnection (package:mongo_dart/src/database/db.dart:281)
#4      DbCollection.modernFindOne (package:mongo_dart/src/database/dbcollection.dart:766)
#5      fetchGuildRules.<anonymous closure> (package:pyrite/src/backend/database.dart:163)
#6      handleQuery (package:pyrite/src/backend/database.dart:60)
<asynchronous suspension>
#7      fetchGuildRules (package:pyrite/src/backend/database.dart:161)
<asynchronous suspension>
#8      fetchGuildRules (package:pyrite/src/backend/storage.dart:89)
<asynchronous suspension>
#9      getGuildRuleCount (package:pyrite/src/backend/storage.dart:179)
<asynchronous suspension>
#10     scanCmd (package:pyrite/src/modules/interactions/scan.dart:86)
<asynchronous suspension>
```

More triage will be needed to determine how long it takes before this occurs. That, along with determining how this could be resolved. The hacky solution would be to restart the instance when the error occurs, but that just masks the issue.

I am not sure if the recent async changes will affect this at all, I do not really anticipate that it does but only time will tell.

**Comment by One-Nub** [comment]
An alternative idea I've had is to go full microservice and spin up a REST API layer that will be referred to for anything related to database/cache storing. Would likely make it in python, take that logic out of Dart entirely since Mongo in Dart is not cooperative.

In a similar vein, if microservices were the path being taken, I would make a service solely for checking users, which result in Pyrite needing 6 things to run for a small Discord bot 🙃. But it would be a learning opportunity; but I am not interesting in spinning up more things to be able to develop Pyrite (and that is outside the scope of this issue).

**Comment by One-Nub** [comment]
From the instance start at `[2024-01-04T17:56:46.790703]`, the connection first failed at `[2024-01-06T15:12:15.688637]` on the gateway instance. This failure errored with the line:
```
[2024-01-06T15:12:15.688637] [SHOUT] [IE]: [MongoDB ConnectionException: connection closed: The socket connection has been reset by peer.
Possible causes:
- Trying to connect to an ssl/tls encrypted database without specifiyng
  either the query parm tls=true or the secure=true parameter in db.open()
- The server requires a key certificate from the client, but no certificate has been sent
- Others, Instance of '_StringStackTrace']
```
After that all consecutive messages are the same (in practice) as the original one.
```
[2024-01-06T15:13:24.983522] [SHOUT] [IE]: [MongoDart Error: No master connection, #0      ConnectionManager.masterConnectionVerified (package:mongo_dart/src/network/connection_manager.dart:19)
#1      Db._masterConnectionVerifiedAnyState (package:mongo_dart/src/database/db.dart:220)
#2      Db._masterConnectionVerified (package:mongo_dart/src/database/db.dart:213)
#3      DbCollection.findOne (package:mongo_dart/src/database/dbcollection.dart:134)
#4      fetchGuildData.<anonymous closure> (package:pyrite/src/backend/database.dart:81)
#5      handleQuery (package:pyrite/src/backend/database.dart:60)
<asynchronous suspension>
#6      fetchGuildData (package:pyrite/src/backend/database.dart:80)
<asynchronous suspension>
#7      fetchGuildWhitelist (package:pyrite/src/backend/storage.dart:108)
<asynchronous suspension>
#8      fetchGuildData (package:pyrite/src/backend/storage.dart:71)
<asynchronous suspension>
#9      on_member_update (package:pyrite/src/modules/gateway/on_member_update.dart:23)
<asynchronous suspension>
]
```

**Comment by One-Nub** [comment]
Looks like what I've hit is the same issue as described here https://github.com/mongo-dart/mongo_dart/issues/228
Pretty much will need to wrap the database logic in a check to make sure the connection is alive, and to reconnect if it isn't.

**Comment by One-Nub** [comment]
Reconnection code has been added in commit fefa64a, we shall see if it fixes it or not in a few days time.

**Comment by One-Nub** [comment]
The added code appears to have fixed the issue for now. The "connection reset by peer" log message still appears, but the database is successfully reconnected.
